set_property PACKAGE_PIN G17 [get_ports readout_0]
set_property IOSTANDARD LVCMOS33 [get_ports readout_0]

set_property PACKAGE_PIN D19 [get_ports {dac_dda_0[13]}]
set_property PACKAGE_PIN D20 [get_ports {dac_dda_0[12]}]
set_property PACKAGE_PIN F20 [get_ports {dac_dda_0[11]}]
set_property PACKAGE_PIN F19 [get_ports {dac_dda_0[10]}]
set_property PACKAGE_PIN G20 [get_ports {dac_dda_0[9]}]
set_property PACKAGE_PIN G19 [get_ports {dac_dda_0[8]}]
set_property PACKAGE_PIN H20 [get_ports {dac_dda_0[7]}]
set_property PACKAGE_PIN J20 [get_ports {dac_dda_0[6]}]
set_property PACKAGE_PIN J19 [get_ports {dac_dda_0[5]}]
set_property PACKAGE_PIN K19 [get_ports {dac_dda_0[4]}]
set_property PACKAGE_PIN L20 [get_ports {dac_dda_0[3]}]
set_property PACKAGE_PIN L19 [get_ports {dac_dda_0[2]}]
set_property PACKAGE_PIN M20 [get_ports {dac_dda_0[1]}]
set_property PACKAGE_PIN M19 [get_ports {dac_dda_0[0]}]

set_property PACKAGE_PIN M17 [get_ports IQWRT_0]
set_property PACKAGE_PIN M18 [get_ports IQCLK_0]
set_property PACKAGE_PIN N16 [get_ports IQSEL_0]
set_property PACKAGE_PIN N15 [get_ports IQRESET_0]

set_property IOSTANDARD LVCMOS33 [get_ports {dac_dda_0[*] IQWRT_0 IQSEL_0 IQCLK_0 IQRESET_0}]
set_property SLEW FAST [get_ports {dac_dda_0[*] IQWRT_0 IQSEL_0 IQCLK_0 IQRESET_0}]
set_property DRIVE 8 [get_ports {dac_dda_0[*] IQWRT_0 IQSEL_0 IQCLK_0 IQRESET_0}]

set_property PACKAGE_PIN F16 [get_ports {Q_1_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q_1_0}]
set_property PACKAGE_PIN F17 [get_ports {Q_2_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q_2_0}]
set_property PACKAGE_PIN G15 [get_ports {Q_3_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q_3_0}]
set_property PACKAGE_PIN H15 [get_ports {Q_4_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q_4_0}]

set_property PACKAGE_PIN L16 [get_ports Trigger_0]
set_property IOSTANDARD LVCMOS33 [get_ports Trigger_0]
